sauce_username: msgpack-lite
sauce_key: "32947ef3-a727-4848-9aee-cebe65df3be4"
name: msgpack-lite
ui: mocha-bdd
html: "test/zuul/ie.html"
scripts:
  - "dist/msgpack.min.js"
browsers:
  - name: ie
    version: "9..latest"
  - name: MicrosoftEdge
    version: "14..latest"
  - name: chrome
    version: "-5..latest"
  - name: firefox
    version: "-5..latest"
  - name: safari
    version: "9..latest"
  - name: ipad
    version: "10.3..latest"
  - name: iphone
    version: "10.3..latest"
  - name: android
    version: "5.1"
